### ISSUE TITLE
No backend available

### ISSUE THREAD

**Issue by awinborne415** [jnweiger/inkscape-silhouette#165]
After hitting send to silhouette and then apply I get a window that says "Inkscape has received addition data from the script executed. The script did not return an error, but this may indicate the results will not be as expected." Then below it says "No backend available." I have to be missing something with my setup. But I cant find any info anywhere about this problem. I have a Cameo 3 plugged up via USB and the item I'm wanting to cut selected.

**Comment by t0b3** [comment]
possibly duplicate of https://github.com/fablabnbg/inkscape-silhouette/issues/129#issuecomment-831709976

**Comment by awinborne415** [comment]
After completely uninstalling Inkscape and Python3-USB this did work
