### ISSUE TITLE
silhouette_multi invoking sendto_silhouette improperly when "Override cutter model" selected

### ISSUE THREAD

**Issue by gwhitney** [jnweiger/inkscape-silhouette#172]
If I use silhouette multi and a value of "Override cutter model" as anything besides `-- as detected --`, the cut fails. The difficulty appears to be that then the value of the `--force_hardware` option has a space in it, but this space is not quoted or escaped in any way, leading to `sendto_silhouette` not properly parsing the arguments.

I'd suggest a workaround of changing all of the spaces to underscores in the "value" fields of the force_hardware section of `sendto_silhouette.inx` and then making the identical changes to the "name" fields of the DEVICE array in `sihouette/Graphtec.py`. I would supply a PR myself, but my repository is out of whack with the github one since I submitted the PR #161 (and I keep hoping that will happen at some point).

**Comment by t0b3** [comment]
@gwhitney in the mean time while waiting for #161 you can still sync & update your master branch and thank make a new branch and PR that one...
