### ISSUE TITLE
Unable to send commands on Pop!_OS to Silhouette Cameo 

### ISSUE THREAD

**Issue by anwxwna** [jnweiger/inkscape-silhouette#177]
Traceback (most recent call last):
  File "sendto_silhouette.py", line 148, in <module>
    import silhouette.read_dump
  File "/usr/share/inkscape/extensions/silhouette/read_dump.py", line 14, in <module>
    from pathlib2 import Path # backport for Python2
ImportError: No module named pathlib2

Silhouette Multi actions is failing with action failed , and the simple send to Silhouette has the following traceback. I have pathlib2 installed as well.

**Comment by ktosiek** [comment]
Hi!
It looks like pathlib2 is still missing for the Python your Inkscape uses.
Which version of Inkscape are you using? Can you show the result of running `apt show inkscape`? How did you install pathlib2, and how did you install inkscape-silhouette?

**Comment by anwxwna** [comment]
the output of `apt show inkscape`
```
Package: inkscape
Version: 0.92.5-1ubuntu1.1
Priority: optional
Section: universe/graphics
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 80.8 MB
Depends: python2:any, libatkmm-1.6-1v5 (>= 2.24.0), libc6 (>= 2.29), libcairo2 (>= 1.15.8), libcairomm-1.0-1v5 (>= 1.12.0), libcdr-0.1-1, libdbus-glib-1-2 (>= 0.88), libfontconfig1 (>= 2.12.6), libfreetype6 (>= 2.2.1), libgc1c2 (>= 1:7.2d), libgcc-s1 (>= 4.0), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.41.1), libglibmm-2.4-1v5 (>= 2.54.0), libgomp1 (>= 4.9), libgsl23 (>= 2.5), libgtk2.0-0 (>= 2.24.0), libgtkmm-2.4-1v5 (>= 1:2.24.0), libgtkspell0 (>= 2.0.10), libjpeg8 (>= 8c), liblcms2-2 (>= 2.2+git20110628), libmagick++-6.q16-8, libpango-1.0-0 (>= 1.37.2), libpangocairo-1.0-0 (>= 1.14.0), libpangoft2-1.0-0 (>= 1.14.0), libpangomm-1.4-1v5 (>= 2.42.0), libpng16-16 (>= 1.6.2-1), libpoppler-glib8 (>= 0.18.0), libpoppler97 (>= 0.86.1), libpopt0 (>= 1.14), libpotrace0, librevenge-0.0-0, libsigc++-2.0-0v5 (>= 2.8.0), libstdc++6 (>= 9), libvisio-0.1-1, libwpg-0.3-3, libx11-6, libxml2 (>= 2.7.4), libxslt1.1 (>= 1.1.25), zlib1g (>= 1:1.1.4)
Recommends: aspell, fig2dev, imagemagick, libimage-magick-perl, libwmf-bin, python-lxml, python-numpy, python-scour
Suggests: dia, inkscape-tutorials, libsvg-perl, libxml-xql-perl, pstoedit, python-uniconvertor, ruby
Homepage: https://inkscape.org
Task: ubuntustudio-video, ubuntustudio-graphics
Download-Size: 14.9 MB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages
```

I installed pathlib2 by running `sudo -H pip3 install pathlib2`  and also `pip3 install pathlib2`

I installed inkscape-silhouette from the .deb file available under releases. I was having an issue with the xmltodict package not being found as well, and i installed that using `sudo apt-get install python-wxgtk3.0 python-xmltodict` but i could not see a similar fix for the pathlib2 issue

**Comment by ktosiek** [comment]
Your Inkscape still uses Python 2, I think Python 3 is only used for Inkscape 1+.
You can try going with your current version, or updating Inkscape.

## Current version
You'll need something like:
* for basic functionality: `sudo apt install python-pathlib2 python-usb`
* for silhouette_multi: `sudo apt install python-wxgtk3.0 python-xmltodict`
* for cutting preview you'd need matplotlib, but I don't see it packages for Python 2 on Ubuntu Focal.

## Update
The updated version doesn't need pathlib2, in Python 3 pathlib is built in.
See steps in the README under [Ubuntu 18.04 or 20.04](https://github.com/fablabnbg/inkscape-silhouette#ubuntu-1804-or-2004).

## Other nit picks
Also, in the future avoid `sudo pip install` and `sudo pip3 install`, they will clash with `sudo apt install`ed packages. You should `sudo pip3 uninstall pathlib2` (it should ask you about deleting a folder or 2, both with pathlib2 in the name) before there are any clashes.

**Comment by anwxwna** [comment]
So i updated my inkscape version, its now currently 1.1

I ran the sudo apt install commands that you mentioned, and i installed the .deb file for the inkscape-sillhouette and this is the error i recieved when i tried to run silhouette-multi

```
Traceback (most recent call last):
  File "silhouette_multi.py", line 17, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

```
I ran ` sudo apt-get install python-wxtools` as well, but i got the same error. I then tried to run `python3 -m pip install wxpython` but that failed to install at all.I believe this command `sudo apt install python-wxgtk3.0` was supposed to address wx?

**Comment by t0b3** [comment]
wanna try with the wx packages for python3? `python3-wx...`

**Comment by anwxwna** [comment]
That doesn't seem to exist.  
I did however run the following `pip install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython` explained [here](https://www.wxpython.org/pages/downloads/) , that was able to install wxPython on my system. 

I tried running silhouette-multi after that, but when i chose run in the small pop-up window, it would quickly show a window silhouette-multi is working please wait, and not show anything.

**Comment by t0b3** [comment]
... [python3-wxgtk4.0](https://packages.ubuntu.com/impish/python3-wxgtk4.0) would be the complete name for ubuntu based distros

**Comment by anwxwna** [comment]
I installed that, but i am getting the same issue, of a window quickly popping up and then closing again. Should I uninstall anything ?

**Comment by t0b3** [comment]
send to silhouette works?

**Comment by anwxwna** [comment]
Yes that opens the window to select the cut settings etc. silhouette_multi does not even open that window

**Comment by t0b3** [comment]
for silhouette_multi you need to upgrade to master. 
v1.25 won't work

**Comment by anwxwna** [comment]
> Download https://github.com/fablabnbg/inkscape-silhouette/archive/master.zip

This one?

**Comment by ktosiek** [comment]
This one is the newest development version, and should work.

**Comment by anwxwna** [comment]
![image](https://user-images.githubusercontent.com/32495320/168193013-a648cb2e-d1d9-4d37-bfde-69648e62dc9e.png)
I get this issue, it also shows it's sending the commands but nothing happens on the side of the machine
