### ISSUE TITLE
Extension didn't open dialog

### ISSUE THREAD

**Issue by dolorosus** [jnweiger/inkscape-silhouette#185]
Hi,

after the upgrade to Inkscape 1.2 (dc2aedaf03, 2022-05-15) I can't get inkscape-silhouette anymore to work.

I Installed the latest version (from the main branch) of inkscape silhoeutte, but after selecting extensions->export->send to silhouette simply nothing happens. No dialog window appears, nothing.

This happens with Win 10 Version	10.0.19044 Build 19044.

USB Device is attached and found:

    c:\Program Files\Inkscape\bin>.\python
    Python 3.9.12 (main, Apr 30 2022, 21:12:07)  [GCC 11.3.0 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import usb.core
    >>> usb.version_info
    (1, 2, 1)
    >>> usb.core.find()
    <DEVICE ID 0b4d:1123 on Bus 000 Address 255>

What can I do to get more information about what's going wrong?

**Comment by t0b3** [comment]
As a first step you may run try to run from the commandline within the folder where inkscape-silhouette is located:
```Shell
python sendto_silhouette.py --help
```
to learn how to run from commandline... i.e.
```Shell
python sendto_silhouette.py --dry_run=True --preview=False --log_paths=True --logfile=silhouette.log examples/testcut_square_triangle.svg
```
any error messages?

**Comment by dolorosus** [comment]
C:\Program Files\Inkscape\share\inkscape\extensions>"c:\Program Files\Inkscape\bin\python.exe" sendto_silhouette.py --dry_run=True --preview=False --logfile=z:\tmp\silhoette.log  ..\examples\testcut_square_triangle.svg
    C:\Program Files\Inkscape\share\inkscape\extensions\sendto_silhouette.py:641: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead  transform = Transform(self.docTransform) * transform
    C:\Program Files\Inkscape\share\inkscape\extensions\sendto_silhouette.py:642: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead  transform = Transform(extra_transform) * transform

Logfile:

    Dry run specified; no commands will be sent to cutter.
    device lookup under windows not tested. Help adding code!
    Silhouette Portrait found on usb bus=0 addr=255
    device init under windows not implemented. Help adding code!
    status=unloaded
    device version: 'Portrait V1.10    '
    Device Version: 'Portrait V1.10    '
    Media=132, cap='blue', name='Print Paper Light Weight'
    toolholder: 1
    speed: 10
    pressure: 10
    Loaded media is expected left-aligned.
    mediabox: (0,0)-(206,300)
    Final bounding box and point counts: {'clip': {'urx': 206, 'ury': 0, 'llx': 0, 'lly': 300.0, 'count': 0}, 'only': False, 'count': 13, 'llx': 0.0, 'urx': 9.375007708333333, 'lly': 9.374991686595417, 'ury': -1.6021737916666666e-05}

    status=ready
     done. 0 min 0 sec


As far as I can see: no errors.


I extracted the `silhouette`, `sendto_silhouette.inx`, `sendto_silhouette.py`, `silhouette_multi.inx`, `silhouette_multi.py` into `C:\Program Files\Inkscape\share\inkscape\extensions` which let  `sendto_silhouette`, `silhouette_multi` appear in the export menu. With this issue.

For testing I put `silhouette`, `sendto_silhouette.inx`, `sendto_silhouette.py`, `silhouette_multi.inx`, `silhouette_multi.py`  ***also*** into the user extension folder `C:\Usersxxx\AppData\Roaming\inkscape\extensions`.  Subsequently it worked and the dialogbox opened, but I have no clue why...

**Comment by t0b3** [comment]
retry again with latest commit. Does it work now?

**Comment by dolorosus** [comment]
`silhouette`, `sendto_silhouette.inx`, `sendto_silhouette.py`, `silhouette_multi.inx`, `silhouette_multi.py` under `C:\Program Files\Inkscape\share\inkscape\extensions` -> No dialogbox
 
 `silhouette`, `sendto_silhouette.inx`, `sendto_silhouette.py`, `silhouette_multi.inx`, `silhouette_multi.py` ***also*** under `C:\Users\xxx\AppData\Roaming\inkscape\extensions` ->Dialogbox appears, but the entries in the menu appear twice

 `silhouette`, `sendto_silhouette.inx`, `sendto_silhouette.py`, `silhouette_multi.inx`, `silhouette_multi.py` ***only*** under `C:\Users\xxx\AppData\Roaming\inkscape\extensions` ->No dialogbox

**Comment by t0b3** [comment]
did you test with this commit in? e219b21d184026dda9ef044d6d41412b1ca2bb98

**Comment by t0b3** [comment]
NB don't copy it in two places at the same time, that will cause confusion...

**Comment by dolorosus** [comment]
Sorry for confusion, I did a pull but...

After replacing with the files from commit `e219b21` it worked fine.

**Many thanks for the fast help!**
