### ISSUE TITLE
Plugin stops working after updating inkscape to 1.2 (1.3 dev also affected)

### ISSUE THREAD

**Issue by JimKnopfIoT** [jnweiger/inkscape-silhouette#187]
I use this great plugin for several months now with a Cameo 4. After updating inkscape from latest 1.1 to the new 1.2 version, the plugin stops working on Windows. The 4 files and the silhouette folder are still present in inkscape/share/inkscape/extension. USB driver is still active. In Inkscape the extension is present in menu but nothing happens after clicking it. I don't get any error log information. 

Same behavior after testing with 1.3 dev Version.

Before the update, i did a backup from inkscape folder. After unrolling the update and using the 1.1 folder again, the Cameo 4 works like before the update.

**Comment by t0b3** [comment]
doublecheck if using the latest main branch helps. most probably duplicate of #185

**Comment by JimKnopfIoT** [comment]
Thank you, latest main branch did it. Works perfect on 1.2 and 1.3 dev.
