### ISSUE TITLE
Error when trying to cut (Inkscape 1.2 - Kubuntu 22.04)

### ISSUE THREAD

**Issue by bybinhabr** [jnweiger/inkscape-silhouette#194]
I received ERROR after updates (system and Inkscape), can't cut anymore :(   :

usage: sendto_silhouette.py [-h] [--output OUTPUT] [--id IDS]
                            [--selected-nodes SELECTED_NODES]
                            [--active-tab ACTIVE_TAB] [-d DASHES]
                            [-a AUTOCROP] [-b BBOXONLY] [-c BLADEDIAMETER]
                            [-C {cameo_12x12,cameo_12x24,no_mat}] [-D DEPTH]
                            [--dummy DUMMY]
                            [-g {mintravel,mintravelfull,matfree,zorder}]
                            [-l SW_CLIPPING]
                            [-m {100,101,102,106,111,112,113,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,300}]
                            [-o OVERCUT] [-M MULTIPASS] [-p PRESSURE]
                            [-P SHARPENCORNERS]
                            [--sharpencorners_start SHARPENCORNERS_START]
                            [--sharpencorners_end SHARPENCORNERS_END]
                            [-r REVERSETOGGLE] [-s SPEED] [-S SMOOTHNESS]
                            [-t {autoblade,cut,pen,default}] [-T {1,2}] [-V]
                            [-w WAIT_DONE] [-x X_OFF] [-y Y_OFF] [-R REGMARK]
                            [--regsearch REGSEARCH] [-X REGWIDTH]
                            [-Y REGLENGTH] [--rego-x REGORIGINX]
                            [--rego-y REGORIGINY] [-e {start,below}]
                            [INPUT_FILE]
sendto_silhouette.py: error: unrecognized arguments: --preview=false --end_offset=0 --orient_paths=natural --fuse_paths=false --log_paths=false --inc_queries=false --append_logs=false --dry_run=false --force_hardware=DETECT

**Comment by t0b3** [comment]
what is your operating system & version? inkscape version? inkscape-silhouette version?
what are the steps you take to reproduce this error?

**Comment by t0b3** [comment]
what is your inkscape-silhouette version?
what are the steps you take to reproduce this error?

**Comment by t0b3** [comment]
I guess updating inkscape-silhouette resolved this issue. Feel free to reopen if it still appears with the latest version...
