### ISSUE TITLE
Invalid value for OPTIONS key, ignoring: 'lastrule'

### ISSUE THREAD

**Issue by mfraser** [jnweiger/inkscape-silhouette#196]
In my syslog I'm seeing invalid rule errors:
Jun 20 08:50:37 Woody systemd-udevd[416]: /usr/lib/udev/rules.d/40-silhouette-udev.rules:1 Invalid value for OPTIONS key, ignoring: 'lastrule'
Jun 20 08:50:37 Woody systemd-udevd[416]: /usr/lib/udev/rules.d/40-silhouette-udev.rules:1 The line takes no effect, ignoring.
Jun 20 08:50:37 Woody systemd-udevd[416]: /usr/lib/udev/rules.d/40-silhouette-udev.rules:2 Invalid value for OPTIONS key, ignoring: 'last_rule'
Jun 20 08:50:37 Woody systemd-udevd[416]: /usr/lib/udev/rules.d/40-silhouette-udev.rules:2 The line takes no effect, ignoring.
Jun 20 08:50:37 Woody systemd-udevd[416]: /usr/lib/udev/rules.d/40-silhouette-udev.rules:4 Invalid value for OPTIONS key, ignoring: 'last_rule'
Jun 20 08:50:37 Woody systemd-udevd[416]: /usr/lib/udev/rules.d/40-silhouette-udev.rules:13 Invalid value for OPTIONS key, ignoring: 'lastrule'

First of all there seems to be both lastrule and last_rule, second 'last_rule' was removed in version 147 or udev - I'm currently using version 248.

I believe it is recommended to use GOTO="end_of_file" instead.

**Comment by t0b3** [comment]
@mfraser this sounds great and I would like to have your contribution as a PR.

**Comment by mfraser** [comment]
> @mfraser this sounds great and I would like to have your contribution as a PR.

https://github.com/fablabnbg/inkscape-silhouette/pull/197
