### ISSUE TITLE
Plugin not working with 1.2

### ISSUE THREAD

**Issue by PipeManMusic** [jnweiger/inkscape-silhouette#198]
Installed Inkscape 1.2 from the official ubuntu PPA and now the silhouette plugin doesn't work. It shows in the extensions but clicking does nothing, no error, nothing shows a warning or error when running inkscape from the command line.

**Comment by t0b3** [comment]
do you run version 1.26 of the plugin?

**Comment by t0b3** [comment]
Maybe a Duplicate of #194 ?

**Comment by PipeManMusic** [comment]
I took a look and it seems I have 1.25 I'll install 1.26 and retest. I reverted versions so I could stay up and running. Mostly wanted 1.2 of inkscape for the eggbot hatch plugin.

**Comment by t0b3** [comment]
1.25 is known to fail with inkscape 1.2.
Duplicate of #194
