### ISSUE TITLE
Cutting slanting ovals instead of circles

### ISSUE THREAD

**Issue by yaxu** [jnweiger/inkscape-silhouette#202]
Hi all,

I'm using the a4 example regmark template with the cameo 4, and am trying to cut circles, but am getting slanted ovals. Could someone point me in the direction of working out what's going wrong please?

![IMG_20220705_143049](https://user-images.githubusercontent.com/27940/177339715-595ca3bd-48ca-4327-9796-16d6e661c545.jpg)

Here's the svg I'm trying to print and cut:

![reg-sticker-a4](https://user-images.githubusercontent.com/27940/177340347-0e2e58ba-6132-4429-9840-a99233063be8.svg)

**Comment by EtherGraf** [comment]
Have you set the correct values 10/10/190/277 in the extension fields?
This must be the case, otherwise it will not work. 

What happens, if you cut without regmarks? Does it improve the situation?

**Comment by yaxu** [comment]
Thanks for the reply, I think I had the x and y the wrong way around in the regmark fields. However with that fixed I do still get ovals. They are no longer slanted though, which is progress!

If I cut without regmarks I do indeed get circles.

So I guess something is wrong here..

![image](https://user-images.githubusercontent.com/27940/177367731-88ac85fd-a176-4a67-8bf0-df95681aae5a.png)

**Comment by yaxu** [comment]
Finally worked out my problem - the 'driverless' driver on my inkjet printer (epson et-2810) wasn't very good, so things were the wrong size/shape as a result. This became apparent when I measured things on the print outs. Installing an actual driver solved it

**Comment by yaxu** [comment]
Well things are improved but I'm still having problems.. The print measures up, but somehow the inkscape plugin cut is scaled up in both directions so nothing aligns. I've tried upgrading inkscape to 1.2.1, and checked the document display units are in mm. The scale there is 0.264583 per user unit which as far as I can tell = 96dpi. I'm not sure what to try next..

![image](https://user-images.githubusercontent.com/27940/181768624-8f32fcb1-ed2b-421e-84dd-7b3f45354a54.png)

**Comment by EtherGraf** [comment]
Your screenshot of the dialog shows an y mark distance of 227, not 277.
Is this corrected already?

**Comment by yaxu** [comment]
Hi @EtherGraf thanks for the thought, yes I corrected that mistake:
![image](https://user-images.githubusercontent.com/27940/181787063-8f4593b2-1094-4997-a592-79ca6db3b6ce.png)

and can't spot anything in other dialogues:
![image](https://user-images.githubusercontent.com/27940/181787511-ed6aa725-77ad-4754-b1cc-b62367bd3673.png)
![image](https://user-images.githubusercontent.com/27940/181787793-58e06079-f9e1-4557-9ffc-2b5b5e9bc7cc.png)

Perhaps something corrupted with the file somehow. I think I'll try reconstructing it from scratch.

**Comment by yaxu** [comment]
Ok with a reconstructed document I got it much closer.. A bit wobbly but aligned. However it didn't work the first time I tried it with the same settings.. So perhaps I have a problem with my cutter not reading the regmarks reliably.. Who knows..

![image](https://user-images.githubusercontent.com/27940/181795703-428aea78-9b67-4d86-a2dd-ee4b199f3d00.png)
