### ISSUE TITLE
Command line use

### ISSUE THREAD

**Issue by tyrosinase** [jnweiger/inkscape-silhouette#219]
I've been chatting with a Blind person about using a Silhouette to make tactile graphics - she can operate a Cricut but their software is not accessible and they've been less-than-cooperative about working on that (surprise, surprise). She's acquired a Cameo 4... but Inkscape is also not accessible.

I know I can use the command line to make Ink/Stitch produce stitch files, but it's absolutely cargo-cult for me, so: is there a way to run inkscape-silhouette from the command line similarly, and if so how would one adjust the speed and pressure and whatnot?

**Comment by t0b3** [comment]
you are welcome to use `sendto_silhouette.py --help` to get further information on the CLI usage.

**Comment by tyrosinase** [comment]
Ah ha: the underlying problem was that I wasn't actually on the most current version.
