### ISSUE TITLE
Syntax Error: future feature annotations

### ISSUE THREAD

**Issue by rboegit** [jnweiger/inkscape-silhouette#223]
Dear all,

I had to setup my machine from scratch and can't get inkscape-silhouette running again.
Old system: Suse Leap 15.2 & 15.3 -->  inkscape-silhouette working fine
New system: Leap 15.4, Inkscape 1.2.1, inkscape-silhouette from main.zip--> Error message below and no communication with the plotter

`Traceback (most recent call last):
  File "sendto_silhouette.py", line 40, in <module>
    import inkex
  File "/usr/share/inkscape/extensions/inkex/__init__.py", line 11, in <module>
    from .extensions import *
  File "/usr/share/inkscape/extensions/inkex/extensions.py", line 34, in <module>
    from .elements import (
  File "/usr/share/inkscape/extensions/inkex/elements/__init__.py", line 9, in <module>
    from ._parser import SVG_PARSER, load_svg
  File "/usr/share/inkscape/extensions/inkex/elements/_parser.py", line 32, in <module>
    from ..interfaces.IElement import IBaseElement
  File "/usr/share/inkscape/extensions/inkex/interfaces/IElement.py", line 5
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
`

I already switched to Python 3.9 (Leap uses 3.6 by default) and installed/updated pyusb for both versions via pip since I assumed that there is a problem with python versions <3.7.  Unluckily, I get the same behavior with both python versions. 
Do you have any ideas what could be wrong?

Many thanks for any hint
Roman

**Comment by t0b3** [comment]
Your issue seems to be your inkscape version isn't compatible with your legacy python version < 3.7. Most probably python 3.6 is still used in your setup. You can lookup the python version in your log output. 
If this is the issue you may ask your distro to upgrade to a decent python version or tweak it yourself :smile:

**Comment by rboegit** [comment]
Bingo, you were right. Although I set the python version via `update-alternatives --config python`, I had to assign the right python version for inkscape as describes [here](https://stackoverflow.com/questions/52046845/changing-the-python-interpreter-for-inkscape).
