### ISSUE TITLE
Multiple Actions confirmation dialog not appearing

### ISSUE THREAD

**Issue by PlantLily** [jnweiger/inkscape-silhouette#229]
Hey! i recently installed pop!_os and went to use my silhouette (cameo 4) with this extension, but the multiple actions dialog seems to be unhappy, when i try to run it, there's nothing after the execute button.
When using the wait for cutter option a dialog is shown by inkscape with the following error:

```
silhouette_multi.py was called via: ['silhouette_multi.py', '--dry_run=false', '--block=true', '--verbose=true', '/tmp/ink_ext_XXXXXX.svg9S23Z1']
Color keys are dict_keys(['colorless', [128, 128, 0], [128, 0, 119]])
save: None
Reassigned 0 colors.
Colors remaining: []
Final colors: ['colorless', [128, 128, 0], [128, 0, 119]]
Color settings: {'colorless': {}, [128, 128, 0]: {}, [128, 0, 119]: {}}
save: None
Traceback (most recent call last):
  File "/usr/share/inkscape/extensions/silhouette/MultiFrame.py", line 373, in run
    if not confirm_dialog(self, "About to perform %d actions, continue?" % len(actions)):
NameError: name 'confirm_dialog' is not defined
```
confirm_dialog is indeed defined so im very confused.
thanks in advance!

**Comment by t0b3** [comment]
@gwhitney do you have any idea or would you need more info?

**Comment by gwhitney** [comment]
Is this likely related to #217 that I am way overdue looking at? (Very sorry, teaching this semester and trying to get a book to my publisher has been very hectic, will try to look as soon as I can.)

**Comment by PlantLily** [comment]
i have reinstalled the wx libraries, still the same issue.
 if it helps im using inkscape 1.2.2

**Comment by t0b3** [comment]
@PlantLily you may try if #217 solves your issue and report back...

**Comment by PlantLily** [comment]
> @PlantLily you may try if #217 solves your issue and report back...

unfortunately, i get a similar result of :
```
silhouette_multi.py was called via: ['silhouette_multi.py', '--dry_run=false', '--block=true', '--verbose=true', '/tmp/ink_ext_XXXXXX.svgHHYZZ1']
Color keys are dict_keys(['colorless'])
save: None
Reassigned 0 colors.
Colors remaining: [[128, 128, 0], [128, 0, 119]]
Final colors: ['colorless']
Color settings: {'colorless': {}}
save: None
Traceback (most recent call last):
  File "/usr/share/inkscape/extensions/silhouette/MultiFrame.py", line 376, in run
    if not Dialog.confirm("About to perform %d actions, continue?" % len(actions)):
TypeError: Dialog.confirm() missing 1 required positional argument: 'question'
```
could it be due to me using inkscape 1.2?

**Comment by t0b3** [comment]
@PlantLily can you also share this specific result using PR #217 over there to make reviewers aware of your result?
not sure for the reason, if it's related to inkscape version (yes it would be interesting if you could downgrade and report :+1: ) or something wx related. 
note the important detail: this time you got a TypeError for missing arg `question`. at least the dialog function is defined :smile:

**Comment by the-jesus** [comment]
Hi @PlantLily, just updated the pull request #217. Can you please check again?

**Comment by PlantLily** [comment]
> Hi @PlantLily, just updated the pull request #217. Can you please check again?

this appears to have worked :D thanks!

**Comment by PlantLily** [comment]
another nugget of potentially useful information, i opted to install locally instead of globally so it'd be easier to purge the plugin between trying different versions and now im getting this error:
```Traceback (most recent call last):
  File "/home/lily/.config/inkscape/extensions/silhouette_multi.py", line 317, in <module>
    e.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 231, in run
    self.save_raw(self.effect())
  File "/home/lily/.config/inkscape/extensions/silhouette_multi.py", line 176, in effect
    self.frame = MultiFrame(
  File "/home/lily/.config/inkscape/extensions/silhouette/MultiFrame.py", line 281, in __init__
    self._load_preset('__LAST__', silent=True)
  File "/home/lily/.config/inkscape/extensions/silhouette/MultiFrame.py", line 355, in _load_preset
    preset = self.colsep.activate_preset(preset_name, silent)
  File "/home/lily/.config/inkscape/extensions/silhouette/ColorSeparation.py", line 19, in activate_preset
    self.extract_settings_from_preset(preset)
  File "/home/lily/.config/inkscape/extensions/silhouette/ColorSeparation.py", line 73, in extract_settings_from_preset
    if message and not silent:
NameError: name 'silent' is not defined
```
this is from the main extension, not the pr from @the-jesus .

**Comment by the-jesus** [comment]
Hi @PlantLily,

yeah, I think that should be fixed by the pull request as well.

**Comment by t0b3** [comment]
@PlantLily can you test again with latest main and report back? THX

@gwhitney @the-jesus can you please make some general testing of `silhouette_multi.py` and report back? Your feedback will help to prepare new release :smile:  THX

**Comment by t0b3** [comment]
I hope it's gone now
