### ISSUE TITLE
Split project into library and plugin

### ISSUE THREAD

**Issue by bmuessig** [jnweiger/inkscape-silhouette#230]
I really appreciate the work done to get this plugin working, but I was wondering why this is all built into one monolithic codebase and not split into a library repository that could be used standalone (as I would need to use it) and an Inkscape plugin repository that uses the library.

This would focus Silhouette device support development in one place instead of requiring the creation of separate project that tracks the changes from here to support headless applications.

**Comment by t0b3** [comment]
@bmuessig what would be your userstory? it could be interesting to eventually integrate such ideas... while ensuring the distribution is kept as a single package :smile:

**Comment by EtherGraf** [comment]
Isn't it the case already?

You can call the sendto_silhouette.py with arguments to plot a svg standalone without even a need of the inkscape plugin.
The inkscape extension does nothing else than calling this script with appropriate arguments.

**Comment by t0b3** [comment]
@bmuessig feel free to reopen and elaborate more on your headless userstory...

**Comment by bmuessig** [comment]
@t0b3 Sorry for the late reply.

My userstory is exactly covered by what EtherGraf mentioned. I want to be able to plot SVGs automatically without any Inkscape involvement. Initially I was looking for an API to include directly into my project, but invoking a command line utility is just fine for me. Thanks!
