### ISSUE TITLE
How do I translate this project?

### ISSUE THREAD

**Issue by renner0e** [jnweiger/inkscape-silhouette#232]
I like this extension how can I help by translating it to german?

**Comment by t0b3** [comment]
your contribution is very welcome. can you setup the translation according to 
https://inkscape.gitlab.io/extensions/documentation/authors/inx-overview.html#third-party-extensions
i.e. use start from https://github.com/fablabnbg/inkscape-silhouette/blob/main/po/inkscape-silhouette.pot
translate the texts
save under po/de.po
test it locally on your system i.e. `make install-local`
```
locale/
├── de
│   └── LC_MESSAGES
│       └── inkscape-silhouette.mo
```
... and finally contribute your translation using a PR

**Comment by t0b3** [comment]
@Renner0E are you still interested to translate to german? this would be great :+1: 
you can simply copy https://github.com/fablabnbg/inkscape-silhouette/blob/main/po/inkscape-silhouette.pot as a starting point and save results in `po/de.po`

**Comment by t0b3** [comment]
@Renner0E ping?

**Comment by t0b3** [comment]
@Renner0E would you like to contribute something within the upcoming weeks? Then you will land in the next release :+1: any questions on how to proceed?
