### ISSUE TITLE
Line cuts seem to be scaled smaller

### ISSUE THREAD

**Issue by henryso** [jnweiger/inkscape-silhouette#235]
Using the following SVG:

![weird-cut](https://user-images.githubusercontent.com/421318/236631988-22e618f8-80da-4c7d-abc3-36a2b0019414.svg)

I get the following cut preview:

![cut-preview](https://user-images.githubusercontent.com/421318/236632055-2e539429-b8fa-48e5-81b3-79e39b6e5bda.png)

This is also how it cuts.  Why are the straight line cuts scaled and cut in the upper left rather than inside the circle as in the SVG?

**Comment by t0b3** [comment]
@henryso which version of inkscape-silhouette did you use? can you retry with latest main branch? can you post a dump of this? this will help to solve you issue

**Comment by henryso** [comment]
@t0b3 I was at commit ee00e4786b0189ac533070cc88466b3035044081 at the time.  I pulled and applied the latest changes (only sendto_silhouette.py changed, now at 696e4e077eaabdb63598e7cd37f7e9bb5b904970).  I get the same result and am attaching the log.

[inkscape-silhouette.log](https://github.com/fablabnbg/inkscape-silhouette/files/11414985/inkscape-silhouette.log)

**Comment by t0b3** [comment]
@henryso which version of inkscape and inkex do you have installed currently? can you retry with inkscape 1.2 and report back?

**Comment by henryso** [comment]
@t0b3 That was it. I upgraded to the latest Inkscape 1.2.2 and corresponding inkex, and it works properly.  Thanks!

**Comment by t0b3** [comment]
@henryso good to know it works now.
I'm keen to understand your previous context - which inkscape had you been using before?

**Comment by henryso** [comment]
@t0b3 I was using 1.1 of Inkscape and corresponding inkex.

**Comment by t0b3** [comment]
@henryso you ran into https://gitlab.com/inkscape/extensions/-/issues/367 which is patched with https://github.com/fablabnbg/inkscape-silhouette/commit/0d40c1de91520ecacb44928a79474aa4cff03d2e now

**Comment by henryso** [comment]
@t0b3 Thanks for looking into it. 1.2.2 works great, so no issues there.
