### ISSUE TITLE
Is this software licensed under GPL-2.0-only, or GPL-2.0-or-later?

### ISSUE THREAD

**Issue by jfly** [jnweiger/inkscape-silhouette#239]
First off, thanks for this software!

I'm looking to package this project in nixpkgs, the question of which license this project uses came up:

- Here's the PR comment where this came to my attention: https://github.com/NixOS/nixpkgs/pull/239349#discussion_r1239717231
- Here's the nix policy about gplv2 vs gplv2Only vs gplv2Plus: https://discourse.nixos.org/t/lib-licenses-gpl3-co-are-now-deprecated/8206/1
- And finally, here are Richard Stallman's words on the whole thing: https://www.gnu.org/licenses/identify-licenses-clearly.html.

Can you provide clarity about which flavor of GPL v2 this code uses? Thanks!

**Comment by jnweiger** [comment]
The code is effectively GPLv2 only.

- setup.py:license='GPL-2.0',
- silhouette/Graphtec.py:# Distribute under GPLv2 or ask.
- misc/test_drive.py:# (c) 2013 jnweiger@gmail.com, distribute under GPL-2.0
- silhouette/convert2dashes.py: [GPL] either version 2 of the License, or (at your option) any later version.
- sendto_silhouette.py:# (C) 2013 jw@suse.de. Licensed under CC-BY-SA-3.0 or GPL-2.0 at your choice.
- silhouette-udev-notify.sh:# (c) 2013, jw@suse.de - All rights reserved. Distribute under GPL-2.0


While the main file sendto_silhouette.py is under a dual license we need to find what applies to the entire package. CC BY-SA-3.0 is not mentioned anywhere else, so we have at least 3 files that only allow GPLv2.

Regarding the hint in Graphtec.y: "Distribute under GPLv2 or ask." - I probably won't object to allow "GPLv2 or later", if someone asks for it.
But: by now the code base has contributions from many different authors, so my vote is insufficient.

I understand that the text of GPLv2 itself contains the suggestion to use it as "or later" https://github.com/fablabnbg/inkscape-silhouette/blob/main/LICENSE#L299
But this package did not follow that suggestion.

**Comment by jnweiger** [comment]
@t0b3 I believe the licensing is pretty clear. Basically, I don't fully follow Richard Stallman's implication, that a license designator 'GPL-2.0' is half way between 'only' and 'or later'. I see it very close to 'only'.
Maybe setup.py should have a more modern "GPL-2.0-only" SPDX identifier?


And @t0b3, @EtherGraf and ... (oh, I cannot even enumerate all the important people here, sorry... ):
Let me take this opportunity to thank you all for your great support in this project! 
Keep running!

**Comment by t0b3** [comment]
@jnweiger thanks for this clarification.
@jfly does this answear your question? or would you prefer to suggest any changes and contact all of the contributors? or maybe any other changes? if so feel free to make a PR...

**Comment by jfly** [comment]
Nope, I just wanted to know the intent. Thank you for the quick responses!
