### ISSUE TITLE
Extension crashes sometimes when using MatFree cutting strategy

### ISSUE THREAD

**Issue by sector-f** [jnweiger/inkscape-silhouette#240]
Like the title says, the extension crashes for me sometimes when I try to use the MatFree cutting strategy. This is with a Silhouette Cameo 4, although I don't know if that matters. (I don't have anything else to test with)

Here's the traceback:

```
Traceback (most recent call last):
  File "/usr/share/inkscape/extensions/sendto_silhouette.py", line 753, in <module>
    e.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 231, in run
    self.save_raw(self.effect())
                  ^^^^^^^^^^^^^
  File "/usr/share/inkscape/extensions/sendto_silhouette.py", line 596, in effect
    self.paths = mf.apply(self.paths)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/inkscape/extensions/silhouette/Strategy.py", line 1017, in apply
    self.simple_barrier()
  File "/usr/share/inkscape/extensions/silhouette/Strategy.py", line 974, in simple_barrier
    last_x = s.process_simple_barrier(sy[0:barrier_idx], barrier_y, last_x=last_x)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/inkscape/extensions/silhouette/Strategy.py", line 842, in process_simple_barrier
    iM = s.pt2idx((A.x+B.x)*.5, (A.y+B.y)*.5 )
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/inkscape/extensions/silhouette/Strategy.py", line 149, in pt2idx
    if 'dup' in self.points[idx].attr:
                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attr'
```

This crash seems to be consistent for any given path: a "bad" path will always cause this error, and a "good" path will never cause this error.

P. S. I have an additional question: which cutting strategy is recommended for use with the Cameo 4's built-in roll feeder?

**Comment by t0b3** [comment]
@sector-f we need more information please add the failing svg and the dump file to this issue so others can try to reproduce...

**Comment by sector-f** [comment]
@t0b3 I've attached an example which crashes for me. And, while creating the file, I may have found some additional information.

I started by typing "Lorem ipsum etc etc" in the Liberation Serif font, and found that this was enough to cause the error. I then went through each individual letter to see which one was causing the crash. I found that the "e" in the first "etc" caused a crash, but the "e" in the second "etc" did _not_ cause a crash. Two identical paths, except one works and one doesn't. So I guess the path's position in the document matters?

Anyways, I deleted everything except those two letters, and I'm still able to reproduce the crash with the left "e" (but not with the right one).

![crash_repro](https://github.com/fablabnbg/inkscape-silhouette/assets/15021843/ee23d1ef-3ae9-478c-8d37-e4ea2f40b08a)

**Comment by sector-f** [comment]
@t0b3 I think this is the dump file you're talking about. If not, let me know how to find/generate the right one.


> Inkscape 1.2.2 (b0a8486541, 2022-12-01)
> Inkex: 1.2.0
> Inkscape-Silhouette: 1.27
> Path: /usr/share/inkscape/extensions/sendto_silhouette.py
> Python: /usr/bin/python3
> Version: 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
> Platform: linux
> Arguments: sendto_silhouette.py --id=text6299 --active-tab=silhouette --x_off=0 --y_off=0 --cuttingmat=no_mat --toolholder=1 --tool=autoblade --media=300 --speed=8 --pressure=14 --depth=2 --preview=true --dashes=false --autocrop=false --bbox-only=false --multipass=1 --reversetoggle=false --endposition=below --end_offset=0 --regmark=false --regsearch=false --regwidth=180 --reglength=230 --regoriginx=15 --regoriginy=20 --wait_done=false --sharpencorners=true --sharpencorners_start=0.1 --sharpencorners_end=0.1 --overcut=0.5 --strategy=matfree --orient_paths=desy --fuse_paths=true --sw_clipping=true --logfile=/home/adam/Documents/stencils/crash.log --log_paths=true --append_logs=false --inc_queries=false --dry_run=false --force_hardware=DETECT --bladediameter=0.9 /tmp/ink_ext_XXXXXX.svg825K71

**Comment by t0b3** [comment]
this is reproducible with `--strategy=matfree` using above [svg](https://user-images.githubusercontent.com/15021843/251634604-ee23d1ef-3ae9-478c-8d37-e4ea2f40b08a.svg)

@jnweiger any idea what happens in https://github.com/fablabnbg/inkscape-silhouette/blob/a1941b6f740466a20dfa116415dd599b1e496302/silhouette/Strategy.py#L149
and results in 
```
  File "/usr/share/inkscape/extensions/silhouette/Strategy.py", line 149, in pt2idx
    if 'dup' in self.points[idx].attr:
                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attr'

**Comment by sector-f** [comment]
I've added some logging to my Strategy.py file to try to track this down. Here's what I have so far:

```
k = 192.08030630184737,135.2862444385251
k not found in points_dict
adding to points: (192.08030630184737, 135.2862444385251)
adding to points_dict: 41
...
adding to points_dict: 58
k = 192.08030630184737,135.2862444385251
dup found at idx = 41
point is (192.08030630184737, 135.2862444385251)
attrs is {'attr': {...}, 'id': 41}
k = 192.08030630184737,135.2862444385251
dup found at idx = 41
point is None
```

1. It originally adds a point at idx 41 successfully
2. It processes more points successfully, getting up to idx 58
3. It encounters a duplicate of idx 41, and handles that successfully
4. The next point is _also_ a duplicate of idx 41, and then it crashes because `self.points[idx]` is `None`

The `process_simple_barrier` method has a `for segment in segments` loop, which is where `pt2idx` is getting called. It seems like the point is getting deleted between one iteration of that loop and the next? I can't find any code that seems to do that though.

Maybe the problem is specifically caused by two identical segments being back-to-back in the `segments` list? I don't have any hard evidence to prove that, but I do think it's interesting that the idx 41 duplicate is looked up once successfully, and the crash only occurs when idx 41 is encountered twice in a row.

**Comment by sector-f** [comment]
Alright, more findings: this issue is triggered by `unlink_segment` being called in `process_simple_barrier`. Currently, this sets things in `self.points` to `None`, but doesn't do anything with `self.points_dict`. If we then encounter a segment where both A and B are sharp, then `pt2idx` gets called, and it crashes because `points_dict` no longer matches `points` correctly.

I've submitted a PR which (hopefully) fixes this by setting the appropriate `points_dict` values to `None` in `unlink_segment`.

@t0b3 can you look at this and see if my explanation and fix are reasonable?
