### ISSUE TITLE
Got IsADirectoryError: [Errno 21] Is a directory: '/usr/share/inkscape/extensions' in Debian GNU/Linux 11 (bullseye) x86_64

### ISSUE THREAD

**Issue by mofosyne** [jnweiger/inkscape-silhouette#244]
Extension Version: [v1.28](https://github.com/fablabnbg/inkscape-silhouette/releases/tag/v1.28)

I'm using vanilla Debian GNU/Linux 11 (bullseye) x86_64 and installed via these two commands `sudo make install` and `sudo apt-get install python3-usb` from the inkscape-silhouette-main extracted folder.

I was able to see the extension in inkscape, but when I press apply this is the error message I got.

```
Traceback (most recent call last):
  File "/usr/share/inkscape/extensions/sendto_silhouette.py", line 753, in <module>
    e.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
    self.save_raw(self.effect())
  File "/usr/share/inkscape/extensions/sendto_silhouette.py", line 552, in effect
    self.log = open(self.options.logfile, mode)
IsADirectoryError: [Errno 21] Is a directory: '/usr/share/inkscape/extensions'
```

Unsure what's the cause, but hope the error message will help.

![image](https://github.com/fablabnbg/inkscape-silhouette/assets/827793/3b152ed5-78f6-4690-a919-6eea641dc99b)

----

On a side note, I also noticed `(org.inkscape.Inkscape:92900): Gtk-CRITICAL **: 10:24:16.729: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GdlSwitcher` error message as well, but appears to be unrelated to this problem (but is likely a slight GUI error in this extention)

**Comment by mofosyne** [comment]
When I comment out the section under `if self.options.logfile`  I get a similar IsADirectoryError error but for `self.cmdfile`

```
    def effect(self):
        if self.options.logfile:
            mode = "a" if self.options.append_logs else "w"
            self.log = open(self.options.logfile, mode)
            if self.tty:
                self.log = teeFile(self.tty, self.log)

        if self.options.cmdfile:
            mode = "ab" if self.options.append_logs else "wb"
            self.cmdfile = open(self.options.cmdfile, mode)
...
```

So somehow this extension is not receiving the full filepath, but only receiving `/usr/share/inkscape/extensions`

**Comment by t0b3** [comment]
Thanks for your feedback. 

Can you try a filepath i.e. `/tmp/silhouette.log` for the log file and report back?

**Comment by mofosyne** [comment]
I've reformatted my computer an installed linux mint instead. So can't help in that regard anymore. Maybe if there is an error, perhaps see if you can add a short message on sending the /tmp/silhouette.log to github issues. I was not aware that's where the log was.

(Though on linux mint, I hit some UX issues that I've logged into https://github.com/fablabnbg/inkscape-silhouette/issues/245 )

**Comment by t0b3** [comment]
The path for the log file is at the users choice. `/tmp/silhouette.log` is just a proposition known to work on linux.
In case you know a good platform agnostic default feel free to open a PR for that.

NB: And indeed we may suggest to submit the log for issue reports. Did you ever work with github issue templates?

**Comment by mofosyne** [comment]
I never used github issues template, but I can see there is a way to make it easier for users to get a structured bug submission form in https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository . I think it be a good idea to create such `.github/ISSUE_TEMPLATE` to streamline bug submissions.

------

Was a bit confused when you mean setting a log file path, but then i found the Log and Dump and I understand what you mean now. I think as a default `/tmp/silhouette.log` is a safe choice as it is deleted on each reboot anyway and will be a safe first point to ask users to locate and copy and paste the content via `cat /tmp/silhouette.log`

![image](https://github.com/fablabnbg/inkscape-silhouette/assets/827793/6634000a-76b4-4d70-b3c2-18cbb8339af2)
