### ISSUE TITLE
Before cutting, it should check if regmark has excessive slanting 

### ISSUE THREAD

**Issue by mofosyne** [jnweiger/inkscape-silhouette#247]
Just had a miscut due to what I think was a misread of the X axis somehow.

There probably should be a prompt if possible before proceeding with the cut if there is excessive compensation detected which may indicate a misread.

On my second attempt on the same paper it cuts correctly.

![PXL_20230803_164744837.jpg](https://github.com/fablabnbg/inkscape-silhouette/assets/827793/9649bc47-b1fb-49ef-ba70-9b19d787095b)

**Comment by EtherGraf** [comment]
To my knowledge this is not possible, because the whole correcion is done standalone by the machine itself. I believe, there is no return message, which could be checked.

Maybe it is possible to give a maximum deviation at the initial call, but I am not aware of such a parameter.
