### ISSUE TITLE
Feature Request: Multi-Action Without Resetting Between Actions

### ISSUE THREAD

**Issue by TapuCosmo** [jnweiger/inkscape-silhouette#250]
Currently, it seems that using Multi-Action simply executes each action consecutively and independently (i.e. runs the regular single-action cut for each action). If registration marks are enabled, this causes each action to need to go through searching for registration marks, which needlessly wastes time and may cause slight misalignments between actions. (If registration marks are not enabled on subsequent actions, then the position reverts to being relative to the initial zero position on power on due to the initial start command sequence being resent.)

Adding an option to perform subsequent actions without resending the initial command sequence would allow for switching between the 2 tool slots (on supported devices) or changing cut parameters without needlessly resetting.

**Comment by t0b3** [comment]
... or wouldn't it be even better to make this the default? Currently not sure how to implement this feature. It might involve refactoring SilhouetteCameo.setup() to consecutively skip the specific init parts or alternatively SilhouetteCameo.plot() to include the tool and toolholder logic...

such a PR would be highly welcome :+1:
