### ISSUE TITLE
Feature Request: autodetect regmark params (offset) by their id

### ISSUE THREAD

**Issue by mofosyne** [jnweiger/inkscape-silhouette#254]
When rendering regmark we should embed metadata so that the plugin knows the regmark settings? E.g. a hidden json text or something

[EtherGraf](https://github.com/EtherGraf) idea was to mark the regmark svg elements with a special svg ID to make them distinguisable from the other content.

If the marks has different id's like e.g. 'regmark-topleft', 'regmark-top-right' and 'regmark-bottom-left' then the extension could read the actual position from the elements itself. This would make the manual settings of position and difference in the settings dialog completely obsolete. (To stay compatible maybe enable this feature only if all settigs are zero)

(context: https://github.com/fablabnbg/inkscape-silhouette/pull/251#issuecomment-1685240119 )

----

This issue is a spinoff a discussion from https://github.com/fablabnbg/inkscape-silhouette/pull/251 . As this is not required for the MVP for render_silhouette_regmark, but more as a nice to have that would increase quality of life for the user. At the moment they just have to reference the text on the doc and manually type it to the plugin regmark settings interface.

**Comment by EtherGraf** [comment]
Thanks for crating a separate issue of this.

This proposed solution would have the advantage: If a user moves the regmarks for whatever reason afterwards to an different position, then the data stays correct. 
It makes no difference if the user modifies a predefined template or the output from the new extension.

Hidden metadata with fixed position values would be wrong from this timepoint on.

**Comment by t0b3** [comment]
IIUC @EtherGraf you'd go for reading the physical position [mm] of the regmarks (detectable by their ID i.e. `regmark-bottom-left`) in sendto_silhouette.py
I think this would be a great way to simplify the workflow :+1:

**Comment by mofosyne** [comment]
For any developers in the future tackling this (since I don't feel like doing this issue ticket), I've updated the render regmark PR to use these element IDs, which is also based on existing template svgs in this repo.

```python
REGMARK_LAYERNAME = 'Regmarks'
REGMARK_LAYER_ID = 'regmark'
REGMARK_TOP_LEFT_ID = 'regmark-tl'
REGMARK_TOP_RIGHT_ID = 'regmark-tr'
REGMARK_BOTTOM_LEFT_ID = 'regmark-bl'
REGMARK_SAFE_AREA_ID = 'regmark-safe-area'
REGMARK_NOTES_ID = 'regmark-notes'
```

You can include this to your script that scans the svg elements to locate the corresponding element and try to figure out the regmark settings. Below is an example of the relevant bits of a regmarked svg doc that the plugin should try and extract from.

```svg
<svg
   width="210mm"
   height="297mm"
   viewBox="0 0 210 297"
...
>
...
<g
   inkscape:groupmode="layer"
   id="regmark"
   inkscape:label="Regmarks"
   sodipodi:insensitive="true">
   <rect
      x="10.0"
      y="10.0"
      width="5"
      height="5"
      id="regmark-tl"
      style="fill:black" />
   <path
      d="M 180 10 L 200 10 L 200 30"
      id="regmark-tr"
      style="fill:none;stroke:black;stroke-width:0.3" />
   <path
      d="M 30 287 L 10 287 L 10 267"
      id="regmark-bl"
      style="fill:none;stroke:black;stroke-width:0.3" />
   <path
      d="M 10 30 L 30 30 L 30 10 L 180 10 L 180 30 L 200 30 L 200 287 L 30 287 L 30 267 L 10 267"
      id="regmark-safe-area"
      style="fill:white;stroke:none" />
   <text
      x="33.0"
      y="292.0"
      id="regmark-notes"
      style="font-size:2.5px">mark distance from document: Left=10.0mm, Top=10.0mm; mark to mark distance: X=190.0mm, Y=277.0mm; </text>
</g>
</svg>
```

You may need to create a parser to extract the origin points from the svg path string... e.g. `"M 180 10 L 200 10 L 200 30"` for top right origin path should extract out `x=200, y=10` as the origin point for it.

**Comment by mofosyne** [comment]
While I'm still don't have the motivation to add this in. I did give a stab at calculating the origin point.

```python
        regmarkG=self.svg.getElementById("regmark")
        if regmarkG is not None:
            regmark_tl_x=float(self.svg.getElementById("regmark-tl").get("x", 0))
            regmark_tl_y=float(self.svg.getElementById("regmark-tl").get("y", 0))
            regmark_tr_d=self.svg.getElementById("regmark-tr").get("d", 0)
            regmark_bl_d=self.svg.getElementById("regmark-bl").get("d", 0)
            self.msg(f"regmark-tl.x: {regmark_tl_x}")
            self.msg(f"regmark-tl.y: {regmark_tl_y}")
            self.msg(f"regmark-tr.d: {regmark_tr_d}")
            self.msg(f"regmark-bl.d: {regmark_bl_d}")
            regmark_tr_origin_x = float(regmark_tr_d.split(" ")[4])
            regmark_bl_origin_y = float(regmark_bl_d.split(" ")[5])
            derived_reg_origin_X = regmark_tl_x
            derived_reg_origin_Y = regmark_tl_y
            derived_reg_width    = regmark_tr_origin_x - regmark_tl_x
            derived_reg_length   = regmark_bl_origin_y - regmark_tl_y
            self.msg(f"derived_reg_origin_X: {derived_reg_origin_X}")
            self.msg(f"derived_reg_origin_Y: {derived_reg_origin_Y}")
            self.msg(f"derived_reg_width   : {derived_reg_width   }")
            self.msg(f"derived_reg_length  : {derived_reg_length  }")
```

outputs this

```
regmark-tl.x: 10.0
regmark-tl.y: 10.0
regmark-tr.d: M 180 10 L 200 10 L 200 30
regmark-bl.d: M 30 287 L 10 287 L 10 267
derived_reg_origin_X: 10.0
derived_reg_origin_Y: 10.0
derived_reg_width   : 190.0
derived_reg_length  : 277.0
```

Which matches `mark distance from document: Left=10.0mm, Top=10.0mm; mark to mark distance: X=190.0mm, Y=277.0mm;`

Just note that my approach may not be the most robust for all permutations of svg, so you need to test quite a bit (hence why I rather not tackle this issue).

But I hope this write up will make it easier for those who want to give this a shot.

----

Copy of svg used in this test

![cameo-4-template](https://github.com/fablabnbg/inkscape-silhouette/assets/827793/ae8c8292-a618-4574-8ff8-eb6368194834)
