### ISSUE TITLE
Cannot find nor start the extension after installation

### ISSUE THREAD

**Issue by KanenasPL** [jnweiger/inkscape-silhouette#267]
System: Artix Linux
Extension installed from AUR Arch repository into /usr/share/inkscape/extensions/
Inkscape 1.3
Device: Silhouette Cameo 4 via USB, detected via CUPS (no driver, though).

Problem:
I cannot find extension (not listed under "Manage extensions...") nor any option related to sending commands to the plotter. I got stuck - please advise.

**Comment by t0b3** [comment]
What do you mean exactly by *cannot find extension*
Do you have the menu **extensions - export - send to silhouette**?

**Comment by KanenasPL** [comment]
Nope. The extensions - export only contains: 
- Export layer slices...
- Guillotine
- _Plot..._ (greyed out)

**Comment by t0b3** [comment]
So that's an issue with AUR package. You may open an issue over there...
The installation location needs to correspond to Inkscapes expectations.
