### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/usr/share/inkscape/extensions'

### ISSUE THREAD

**Issue by wuffi** [jnweiger/inkscape-silhouette#270]
Thanks for making this plugin available to the community.
It is certainly helpful, but I get the following error message when pressing the 'Apply' button in the 'Extensions > Send to Silhouette' dialog:
```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "sendto_silhouette.py", line 753, in <module>
    e.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
    self.save_raw(self.effect())
  File "sendto_silhouette.py", line 552, in effect
    self.log = open(self.options.logfile, mode)
IsADirectoryError: [Errno 21] Is a directory: '/usr/share/inkscape/extensions'
```
I do a bit of programming in *Python*, but here I'm lost: well, yes, `/usr/share/inkscape/extensions` is a directory. I had already deleted `~/.config/inkscape/extensions` due to the same error message, which didn't help.

I followed the installation instructions, but have to admit that I'm still using *Ubuntu 18.04*, which is slightly outdated.

**Comment by wuffi** [comment]
Stupid me: When choosing one of  the older releases (from 2019), everything works perfectly.

Apologies for the inconveniences and thanks again for making the plugin available!

**Comment by t0b3** [comment]
@wuffi thanks for reporting. might be fixed in the latest version from TRUNK... you may retry this one and report back...
