### ISSUE TITLE
Feature request: Reparse registration marks after configurable number of contours / cutting distance

### ISSUE THREAD

**Issue by IrgendwerA8** [jnweiger/inkscape-silhouette#274]
Hi,
(I've tried to browse if this feature is already available but found nothing - apologies if I missed something.)

I cut often many small labels. Due to the limited repetition accuracy of the plotter the cuts get more and more misaligned over time.
My feature request consist in re-reading the registration marks after a configurable number of processed outlines or (alternatively) distance to re-align the cutting.

**Comment by t0b3** [comment]
@IrgendwerA8 recently there is an ongoing contribution of the opposite feature `only read regmarks once` https://github.com/fablabnbg/inkscape-silhouette/pull/266. so feel free to step up and enhance from there. 

or you could simply use the silhouette multi action w/o above feature, thus recalibrating regmarks...

WDYT?

**Comment by IrgendwerA8** [comment]
I guess I have to browse for the possibilities of the multi action, to achieve what I like...

Currently my work-around consists in having the original sheet divided in several sheets with partly coverage of the full cutting job and launch cutting on the same print for all those (sub-)pages to have the repeated reading of the marks.

**Comment by t0b3** [comment]
exactly, multi action will recalibrate for each layer - except you enable the new feature once available...
... and in case you would like something different feel free to contribute :smile:
