### ISSUE TITLE
<frozen importlib._bootstrap>:671: ImportWarning: DynamicImporter.exec_module() not found;

### ISSUE THREAD

**Issue by CatherineLE** [jnweiger/inkscape-silhouette#284]
Hi the Team !

I have install from scratch after OS re installed. 
I follow the instructions.
I have python 3.10 - last inkscape version - pop_os 

I did not find a solution online for my problem.
1/ I open Inkscape >> OK
2/ Extention menu > export > send to silhouette > >OK
3/ I click Apply
here what I see:
![Screenshot from 2024-01-14 15-13-57](https://github.com/fablabnbg/inkscape-silhouette/assets/46371678/43034bc6-14d6-4262-abfa-1c80aa1807bf)
4/ so I cancel and I see : 
![Screenshot from 2024-01-14 15-16-23](https://github.com/fablabnbg/inkscape-silhouette/assets/46371678/b794a0ab-1f4d-4904-a9c6-d5e8463c2983)

-----
What I have done:
1/ I upgrade from python 3.10 to python3.11 >> did not work
2/ I paste :"python-interpreter="/usr/bin/python3.11" in the preference.xml file >> did not work
3/ I import gi library and import Gtk module by the terminal, python import works well but not in inkscape environement >> did not work
4/I updrage other libraries like pygobject3 and  python-matplotlib, it works in the terminal but has no effect in inkscape environement >> did not work.

If someone has a solution it would be super great !!!

Thanks to the team for your support !

**Comment by t0b3** [comment]
... and what happens if you press `wait` and wait for the plugin to send the commands to the plotter ?

**Comment by CatherineLE** [comment]
that is an idea ! unfortunately it does not work. The screen stay like this for ever.
![Screenshot from 2024-01-14 17-22-38](https://github.com/fablabnbg/inkscape-silhouette/assets/46371678/0f3639e2-0bd5-4874-952b-5bab22152607)

**Comment by t0b3** [comment]
can you provide the full logfile `log and dump -> save log messages in file` ?

**Comment by t0b3** [comment]
possibly related https://github.com/fablabnbg/inkscape-silhouette/issues/259

**Comment by CatherineLE** [comment]
Yes I already import gtk and matplotlib it works well on terminnal, but has no effect in inkscape. Where can I find the logfile ?

**Comment by t0b3** [comment]
you'll find the logfile where ever you specify the logfile path
![image](https://github.com/fablabnbg/inkscape-silhouette/assets/5751047/229244d2-6aad-41c5-aa9f-9603ed6bded2)

or alternatively you can run the plugin on the cmdline and use `--logfile /path/to/logfile.log`

**Comment by CatherineLE** [comment]
Thank you ! here the logfile 
[silhouette_inkscape.log](https://github.com/fablabnbg/inkscape-silhouette/files/13941199/silhouette_inkscape.log)

**Comment by CatherineLE** [comment]
Here the logfile with the 2  checked boxes: 

[silhouette_inkscape.log](https://github.com/fablabnbg/inkscape-silhouette/files/13941219/silhouette_inkscape.log)

**Comment by t0b3** [comment]
a) what is the output and the logfile  if you launch the command on the cmdline manually and subsequently confirm `CUT` ?

```
/usr/bin/python3 /usr/share/inkscape/extensions/sendto_silhouette.py --x_off=0.00 --y_off=0.00 --cuttingmat=portrait_8x12 --toolholder=1 --tool=cut --media=134 --speed=0 --pressure=0 --depth=-1 --dashes=false --autocrop=false --bbox-only=false --multipass=1 --reversetoggle=false --endposition=start --end_offset=0.0 --regmark=false --regsearch=false --regwidth=180.0 --reglength=230.0 --regoriginx=15.0 --regoriginy=20.0 --wait_done=false --sharpencorners=false --sharpencorners_start=0.1 --sharpencorners_end=0.1 --overcut=0.5 --strategy=zorder --orient_paths=natural --fuse_paths=true --sw_clipping=true --logfile=/tmp/silhouette_inkscape.log --log_paths=false --append_logs=false --inc_queries=true --dry_run=false --force_hardware=DETECT --bladediameter=0.9 --preview=true /path/to/your.svg
```
... where you provide the path to your SVG as the last parameter

b) and it would also interesting to double check the output and the logfile if you turn off preview by using `--preview=false`...

**Comment by CatherineLE** [comment]
Hi !

I have good news. It works through the command lines. So I will use the command lines to use it ! I have noticed that when preview=false there is no error message. So I tried to use the inkscape interface without preview, and nothing happened. Here the results: 
![Screenshot from 2024-01-16 14-22-26](https://github.com/fablabnbg/inkscape-silhouette/assets/46371678/17125384-3a40-4d86-9b3b-41c626ee7f0a)
![Screenshot from 2024-01-16 14-29-47](https://github.com/fablabnbg/inkscape-silhouette/assets/46371678/f34963a5-2b06-4936-81e4-c06a77b8b9bf)

**Comment by CatherineLE** [comment]
the logfile : 

[silhouette_inkscape.log](https://github.com/fablabnbg/inkscape-silhouette/files/13950878/silhouette_inkscape.log)


Thanks a lot !

**Comment by t0b3** [comment]
In Inkscape you may disable the option **dry run** and try again

**Comment by CatherineLE** [comment]
OMG it works !! I just have a pop up windows that s says "inkscape is not responding". I just have to close it.

It was so hard to make it works.. I am very glad ! thank you very much !

**Comment by t0b3** [comment]
that's great news :smile: enjoy then
