### ISSUE TITLE
Here's how I  installed the extension on Fedora (Workstation 40)

### ISSUE THREAD

**Issue by daviddarts** [jnweiger/inkscape-silhouette#292]
I noticed you don't currently include instructions for installing the inkscape-silhouette extension under Fedora. In case this is helpful, I've installed the extension on Fedora Workstation 40 (fresh install) by doing the following:

**1. Install the necessary packages:**
`sudo dnf install python3-pyusb python3-matplotlib  make`

**2. Clone the inkscape-silhoutte repo and make/install the extension:**
`git clone https://github.com/fablabnbg/inkscape-silhouette.git`

`cd inkscape-silhouette/`

`sudo make install`

**3.  Add a new rule to the udev device manager:**
I did run into the udev issue which I resolved (as per the in-extension instructions) by creeating a 99-graphtec-silhouette.rules file:
`sudo nano /etc/udev/rules.d/99-graphtec-silhouette.rules`

And adding the following rule:
`SUBSYSTEM=="usb", ATTR{idVendor}=="0b4d", ATTR{idProduct}=="1137", MODE="666"`

Finally, I loaded the file with:
`sudo udevadm trigger`

**Comment by t0b3** [comment]
@daviddarts feel free to contribute to the README

**Comment by t0b3** [comment]
Closed by #293
