### ISSUE TITLE
No backend available (WIN 10 / Cameo 5)

### ISSUE THREAD

**Issue by Zaza193** [jnweiger/inkscape-silhouette#301]
Few weeks ago i easily make this extantion work on my freinds laptop.So i bought myself a laptop, but unfortunately could not make it work.On both laptops i install "inkscape-1.3_2023-07-21"

Stages : 

1.first i run into the problem of "no module named pip" , that error was not happen on first laptop.With some help from Google i overcome it

2. i run into "No backend available" when trying to send my project to my cameo through inkscape.That problem i could not solve((

 if someone could helo it would be great))

p.s tried inkscape-1.1 same thing

p.s.s tried multiple action to see what would happen and it said 

Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette_multi.py", line 316, in <module>
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette_multi.py", line 153, in effect
    import wx
ModuleNotFoundError: No module named 'wx'

**Comment by t0b3** [comment]
@Zaza193 you may prefer to get sendto_silhouette to work. any testing and contributions wrt cameo 5 are welcome :+1: 

the silhouette multi error seems related to missing wxgtk on your system. it would be wonderful to enhance the install steps for windows :smile:

**Comment by Zaza193** [comment]
> you may prefer to get sendto_silhouette to work

i reinstall this extantion like a hundred times + while doing so updating my Windows and uploading some stuff.At the end it all works out)) i believe problem was in Microsoft Visual C++ and Visual Studio components. When i reinstall them , all started to work as it should
