### ISSUE TITLE
Error in Carriage movement while trying to read Reg.Marks (Cameo5/Win 10)

### ISSUE THREAD

**Issue by Zaza193** [jnweiger/inkscape-silhouette#303]
Using tamplate as guide i make my own Reg.Marks . They are much smaller than template, and as big as smallest possible in SS , like 5 mm in width and length. 

My Cameo reads first reg.mark/square just fine, but when moving down to second reg.mark it dont go straight down, it moves 5-10 mm to the right and missing that mark. Don’t know why.

Yhen I changed Y-Axis distance it traveled either futher down on the page or not so much. When i changed X-axis it dont change anything, because i assume that is only matter when plotter travels to third reg.mark.

Need advice ❤️‍🔥

p.s i made my own reg.marks because my Cameo just can’t read such long reg.marks correctly for some reason. Even when i used them in SS , if they were bigger or thicker than “base” ones , my plotter started to miss every cut 

p.s apperantly it also does even with tamplate , but because its marks are longer Cameo still recognized them

**Comment by Zaza193** [comment]
i changed "self.send_command("TB51,400")   # length of regmarks " in Graphtec to self.send_command("TB51,100")
and Cameo started to go where i want it.now it could read all my reg.marks.

however it still cuts off , i am trying to make work properly.Plus cutting cutting area now not matching my needs now , but i am working on that too.

**Comment by t0b3** [comment]
@Zaza193 feel free to submit a PR in case you propose a correction in the plugin code...
