### ISSUE TITLE
Extension not working with Debian 12.7 and Inkscape 1.3.2 and 1.2.2

### ISSUE THREAD

**Issue by lucasub** [jnweiger/inkscape-silhouette#310]
Hello, 
after clone git repository, I install the plugin by command "make install-local" to ~/.config/inkscape/extensions path.
The version of silhouette is 1.29

I try to send command by inkscape (version 1.2.2) I received this error:
/usr/bin/python3: can't find '__main__' module in '/home/luca/.config/inkscape/extensions'

I try also with inkscape 1.4 from appimage and the message is: "No backend available"
In the console, I see the log: "Python: /tmp/.mount_InkscawbUL83/usr/bin/python3.8" but python3.8 is wrong because I have Python3.11

How can resolve the problem?
Thank you
Luca S.

**Comment by EtherGraf** [comment]
Just tested on a fresh install in a vm on debian 12.7. Installed inkscape 1.2.2 from apt package and current inkscape-silhouette from git repo. Works as expected. 

For the make process I had to install additional package:
apt install gettext

To run I had to install additional package:
apt install python3-cssselect python3-matplotlib

I cannot confirm the error message with missing main module. 
Do you have other extensions installed in parallel?
Try for testing purposes to move the complete ~/.config/inkscape/extensions out of the way and start with a fresh one. (It was empty in my installation at start)

**Comment by t0b3** [comment]
@lucasub I hope you managed to get your installation to work with the above instructions :smile: 

nb: appimage installations are known to end frequently up in troubles exactly for the missing python and usb integration with your system. they are therefore not supported nor expected to work :wink:

**Comment by lucasub** [comment]
Inkscape generate this command to send to solhouette:

sendto_silhouette.py --active-tab=silhouette --x_off=0.20 --y_off=-0.90 --cuttingmat=cameo_12x12 --toolholder=1 --tool=cut --media=300 --speed=5 --pressure=7 --depth=0 --preview=false --dashes=false --autocrop=false --bbox-only=false --multipass=1 --reversetoggle=false --endposition=start --end_offset=0.0 --regmark=true --regsearch=true --regoriginx=24.0 --regoriginy=10.0 --regwidth=270.0 --reglength=175.0 --wait_done=false --sharpencorners=false --sharpencorners_start=0.1 --sharpencorners_end=0.1 --overcut=0.5 --strategy=zorder --orient_paths=natural --fuse_paths=true --sw_clipping=true --log_paths=false --append_logs=false --inc_queries=false --dry_run=false --force_hardware=DETECT --bladediameter=0.9 /tmp/ink_ext_XXXXXX.svgMSVSV2

From terminal the error is: sendto_silhouette.py command not found.

I send from terminal /usr/bin/python3 sendto_silhouette.py --active-tab=silhouette --x_off=0.20 --y_off=-0.90 --cuttingmat=cameo_12x12 --toolholder=1 --tool=cut --media=300 --speed=5 --pressure=7 --depth=0 --preview=false --dashes=false --autocrop=false --bbox-only=false --multipass=1 --reversetoggle=false --endposition=start --end_offset=0.0 --regmark=true --regsearch=true --regoriginx=24.0 --regoriginy=10.0 --regwidth=270.0 --reglength=175.0 --wait_done=false --sharpencorners=false --sharpencorners_start=0.1 --sharpencorners_end=0.1 --overcut=0.5 --strategy=zorder --orient_paths=natural --fuse_paths=true --sw_clipping=true --log_paths=false --append_logs=false --inc_queries=false --dry_run=false --force_hardware=DETECT --bladediameter=0.9 /tmp/ink_ext_XXXXXX.svgMSVSV2

if work well.

Bye
Luca

**Comment by t0b3** [comment]
@lucasub ... this looks like an issue with calling python
what happens if you call `/usr/bin/env python3` ?

**Comment by lucasub** [comment]
Hello to all. I resolve the problem.
In /usr/share/inkscape/extensions there were old silhouette files. I remove it and not work well.
Sorry for disturb.

Bye
Luca S.
