### ISSUE TITLE
Silhouette Portrait 4

### ISSUE THREAD

**Issue by JoshCodeStuff** [jnweiger/inkscape-silhouette#311]
Has anyone tested this plugin with a Silhouette Portrait 4? I am in the market for a cutting machine and want to make sure I can find one that will work with Linux before I take the plunge.

I run Arch Linux as my daily driver.

Thanks!

**Comment by t0b3** [comment]
@JoshCodeStuff I guess not yet - feel free to add your PR once you got one to add it to the list of supported devices :+1:

**Comment by JoshCodeStuff** [comment]
I have now confirmed that the Silhouette Portrait 4 works! I added a pull request.

**Comment by JoshCodeStuff** [comment]
I have now confirmed that the Silhouette Portrait 4 works! I added a pull request.

**Comment by t0b3** [comment]
@JoshCodeStuff can you open a pull request in https://github.com/fablabnbg/inkscape-silhouette - this way I can merge it :smile: (the other one you opened is just in your repo - unable to treat that one)

**Comment by JoshCodeStuff** [comment]
> @JoshCodeStuff can you open a pull request in https://github.com/fablabnbg/inkscape-silhouette - this way I can merge it 😄 (the other one you opened is just in your repo - unable to treat that one)

Could you tell I don't do pull requests often? haha, sorry about that. Fixed it!

**Comment by t0b3** [comment]
@JoshCodeStuff well done - thanks :smile:
