### ISSUE TITLE
windows setup feedback/cry for help

### ISSUE THREAD

**Issue by kohlqez** [jnweiger/inkscape-silhouette#313]
I'm not the most tech savvy guy, but I can't follow the windows setup instructions at all. It seems like the file names/locations don't match instructions, for example I can't find a 'x86\libusb0_x86.dll' file (to be renamed per instructions)  or a 'C:\Program Files\Inkscape\share\extensions' (to extract silhouette files to, I have the latest version of inkscape installed, but the closest thing is the 'extensions' folder with a 'cache' subfolder ) anywhere on my computer. The file 'inkscape-silhouette-master' appears to have changed to 'inkscape-silhouette-main' without that change being reflected in the instructions, which is confusing. Also, the steps to 'Download and unpack http://sourceforge.net/projects/pyusb/
cd C:\Python27\Lib\pyusb-1.0.0b1
\Python27\python.exe setup.py install' have me baffled. I am not sure if it relates to more changed file names or my general lack of technical expertise, but this doesn't make sense to me, I need some more words in my instructions. 
The last several steps are pretty unclear. Based on my inability to follow the preceding instructions I doubt I wield the necessary magics for those steps.
I'm pretty bummed. I really don't wanna have to use the Silhouette Studio, can anybody help me out or suggest another alternative to using Studio?

**Comment by t0b3** [comment]
@kohlqez your experience of mismatching names or locations may be due the Wiki which is clearly outdated :stuck_out_tongue_winking_eye: ... 

I guess you feel more comfortable with the [Readme](https://github.com/fablabnbg/inkscape-silhouette/blob/main/README.md) :smiley:

**Comment by t0b3** [comment]
deprecated instructions have been dropped
